# Git-sql-server-deployment.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-server-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/sql-server"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-deployment
spec:
  replicas: 1  # Number of replicas increased to 2
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        args:
          - clone
          - --single-branch
          - --depth=1
          - https://github.com/kuduba/SQL1.git
          - /scripts
        volumeMounts:
        - name: script-volume
          mountPath: /scripts

      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "YourStrong!Passw0rd"  # Replace with a secure password
        - name: MSSQL_PID
          value: "Express"
        volumeMounts:
        - name: sql-server-storage
          mountPath: /var/opt/mssql
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: sql-server-storage
        persistentVolumeClaim:
          claimName: sql-server-pvc
      - name: script-volume
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: sql-server-service
spec:
  type: NodePort
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 30001
  selector:
    app: sql-server
